### ISSUE TITLE
Jetson Xavier NX, 2 Tests failed

### ISSUE THREAD

**Issue by fhmattsson** [RidgeRun/gst-interpipe#52] opened 2020-07-24 06:31 UTC
Ran the make check and got two errors

PASS: gst/test_allow_renegotiation_property
PASS: gst/test_anonymous_connection
PASS: gst/test_block_switch
PASS: gst/test_buffer_properties
PASS: gst/test_caps_renegotiation
FAIL: gst/test_enable_sync
PASS: gst/test_get_caps
PASS: gst/test_hot_plug
PASS: gst/test_in_bounds_events
FAIL: gst/test_interpipe_synchronization
PASS: gst/test_invalid_caps
PASS: gst/test_node_name_removed
PASS: gst/test_out_of_bounds_events
PASS: gst/test_out_of_bounds_upstream_events
PASS: gst/test_reconfigure_event
PASS: gst/test_set_caps

**Comment by jcaballeros** [comment] 2020-07-31 22:43
Hi @fhmattsson,

Thanks for reporting the issue, I was able to reproduce it and will debug this.

**Comment by jcaballeros** [comment] 2020-07-31 23:00
Duplicate of #49

**Comment by jcaballeros** [comment] 2020-08-13 15:58
Hi,

This issue has been resolved in v1.1.2.

**Closed by jcaballeros** 2020-08-13 15:58 UTC
Labels: bug, duplicate
