### ISSUE TITLE
interpipe using h264 data

### ISSUE THREAD

**Issue by dagmcr** [RidgeRun/gst-interpipe#50] opened 2020-06-05 13:17 UTC
Hi guys,

I'm trying to use `gst-interpipe` to comunicate 2 pipelines using h264 data (and not RAW data).

This example works so far:

```
gst-launch-1.0 \
videotestsrc ! interpipesink name=vts \
interpipesrc listen-to=vts ! autovideosink
```

The idea is to include `interpipe` components in this simple pipeline:

```
gst-launch-1.0 videotestsrc ! queue ! x264enc ! \
queue ! avdec_h264 ! autovideosink
```

So, here the result:

```
gst-launch-1.0 videotestsrc ! queue ! x264enc ! \
interpipesink name=vts \
interpipesrc listen-to=vts ! \
queue ! avdec_h264 ! autovideosink
```

With debug level 3, decoder prints this warning:

```
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
0:00:00.081900235 17456 0x5591b575e360 FIXME                default gstutils.c:3980:gst_pad_create_stream_id_internal:<interpipesrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:00.081920200 17456 0x5591b575e400 FIXME                default gstutils.c:3980:gst_pad_create_stream_id_internal:<videotestsrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Redistribute latency...
Redistribute latency...
0:00:00.117136387 17456 0x5591b575e2a0 WARN            videodecoder gstvideodecoder.c:2423:gst_video_decoder_chain:<avdec_h264-0> Received buffer without a new-segment. Assuming timestamps start from 0.
```

And level 9, latest traces are:

```
0:00:01.588387245 17988 0x555c68d40ea0 DEBUG             bufferpool gstbufferpool.c:244:mark_meta_pooled:<videobufferpool1> marking meta 0x7f3dec003d30 as POOLED in buffer 0x7f3de85b0a20
0:00:01.588396082 17988 0x555c68d40ea0 LOG               bufferpool gstbufferpool.c:286:do_alloc_buffer:<videobufferpool1> allocated buffer 2/0, 0x7f3de85b0a20
0:00:01.588405068 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstobject.c:236:gst_object_ref:<videobufferpool1> 0x7f3de8014ad0 ref 3->4
0:00:01.588414652 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstminiobject.c:721:gst_mini_object_replace: replace (nil) (0) with 0x7f3de85b0a20 (1)
0:00:01.588422842 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstminiobject.c:465:gst_mini_object_ref: 0x7f3de85b0a20 ref 1->2
0:00:01.588432495 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstminiobject.c:721:gst_mini_object_replace: replace 0x7f3de85b0a20 (2) with (nil) (0)
0:00:01.588440388 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstminiobject.c:647:gst_mini_object_unref: 0x7f3de85b0a20 unref 2->1
0:00:01.588451188 17988 0x555c68d40ea0 LOG               GST_BUFFER gstbuffer.c:1797:gst_buffer_map_range: buffer 0x7f3de85b0a20, idx 0, length 1, flags 0003
0:00:01.588459545 17988 0x555c68d40ea0 LOG               GST_BUFFER gstbuffer.c:241:_get_merged_memory: buffer 0x7f3de85b0a20, idx 0, length 1
0:00:01.588467800 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstminiobject.c:465:gst_mini_object_ref: 0x7f3dec0e0f00 ref 1->2
0:00:01.588477913 17988 0x555c68d40ea0 TRACE            GST_LOCKING gstminiobject.c:220:gst_mini_object_lock: lock 0x7f3dec0e0f00: state 00010000, access_mode 3
0:00:01.588487490 17988 0x555c68d40ea0 LOG               GST_BUFFER gstbuffer.c:1797:gst_buffer_map_range: buffer 0x7f3de85b0a20, idx 0, length 1, flags 0003
0:00:01.588495622 17988 0x555c68d40ea0 LOG               GST_BUFFER gstbuffer.c:241:_get_merged_memory: buffer 0x7f3de85b0a20, idx 0, length 1
0:00:01.588504395 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstminiobject.c:465:gst_mini_object_ref: 0x7f3dec0e0f00 ref 2->3
0:00:01.588512941 17988 0x555c68d40ea0 TRACE            GST_LOCKING gstminiobject.c:220:gst_mini_object_lock: lock 0x7f3dec0e0f00: state 00010103, access_mode 3
0:00:01.588521980 17988 0x555c68d40ea0 LOG               GST_BUFFER gstbuffer.c:1797:gst_buffer_map_range: buffer 0x7f3de85b0a20, idx 0, length 1, flags 0003
0:00:01.588529984 17988 0x555c68d40ea0 LOG               GST_BUFFER gstbuffer.c:241:_get_merged_memory: buffer 0x7f3de85b0a20, idx 0, length 1
0:00:01.588538429 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstminiobject.c:465:gst_mini_object_ref: 0x7f3dec0e0f00 ref 3->4
0:00:01.588546948 17988 0x555c68d40ea0 TRACE            GST_LOCKING gstminiobject.c:220:gst_mini_object_lock: lock 0x7f3dec0e0f00: state 00010203, access_mode 3
0:00:01.588555432 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstminiobject.c:465:gst_mini_object_ref: 0x7f3de85b0a20 ref 1->2
0:00:01.588564226 17988 0x555c68d40ea0 LOG                    libav gstavviddec.c:822:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> linesize 384, data 0x7f3dec0e0fc0
0:00:01.588572252 17988 0x555c68d40ea0 LOG                    libav gstavviddec.c:822:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> linesize 192, data 0x7f3dec0f95c0
0:00:01.588580850 17988 0x555c68d40ea0 LOG                    libav gstavviddec.c:822:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> linesize 192, data 0x7f3dec0ff740
0:00:01.588588939 17988 0x555c68d40ea0 LOG                    libav gstavviddec.c:822:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> linesize 0, data (nil)
0:00:01.588596680 17988 0x555c68d40ea0 LOG                    libav gstavviddec.c:822:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> linesize 0, data (nil)
0:00:01.588605731 17988 0x555c68d40ea0 LOG                    libav gstavviddec.c:822:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> linesize 0, data (nil)
0:00:01.588613379 17988 0x555c68d40ea0 LOG                    libav gstavviddec.c:822:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> linesize 0, data (nil)
0:00:01.588621004 17988 0x555c68d40ea0 LOG                    libav gstavviddec.c:822:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> linesize 0, data (nil)
0:00:01.588630068 17988 0x555c68d40ea0 LOG                    libav gstavviddec.c:837:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> returned frame 0x7f3de85b0a20
0:00:01.588696897 17988 0x555c68d40ea0 LOG             videodecoder gstvideodecoder.c:4097:gst_video_decoder_get_max_decode_time:<avdec_h264-0> earliest 99:99:99.999999999, frame deadline 0:00:00.066666666, deadline +2562047:47:16.854775807
0:00:01.588707874 17988 0x555c68d40ea0 DEBUG                  libav gstavviddec.c:1687:gst_ffmpegviddec_video_frame:<avdec_h264-0> return flow ok, got frame: 0
0:00:01.588716494 17988 0x555c68d40ea0 TRACE            GST_LOCKING gstminiobject.c:280:gst_mini_object_unlock: unlock 0x7f3df0214030: state 00010101, access_mode 1
0:00:01.588724192 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstminiobject.c:647:gst_mini_object_unref: 0x7f3df0214030 unref 2->1
0:00:01.588732123 17988 0x555c68d40ea0 TRACE                default gstvideoutils.c:136:gst_video_codec_frame_unref: 0x7f3df01f4710 unref 3->2
0:00:01.588742508 17988 0x555c68d40ea0 DEBUG         GST_SCHEDULING gstpad.c:4329:gst_pad_chain_data_unchecked:<avdec_h264-0:sink> called chainfunction &gst_video_decoder_chain with buffer 0x555c68defea0, returned ok
0:00:01.588751469 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstobject.c:263:gst_object_unref:<avdec_h264-0> 0x555c68ded650 unref 2->1
0:00:01.588760276 17988 0x555c68d40ea0 TRACE        GST_REFCOUNTING gstobject.c:263:gst_object_unref:<avdec_h264-0:sink> 0x555c68d2b5b0 unref 2->1
0:00:01.588768420 17988 0x555c68d40ea0 DEBUG         queue_dataflow gstqueue.c:1516:gst_queue_loop:<queue1> queue is empty
0:00:01.588781262 17988 0x555c68d40ea0 LOG           queue_dataflow gstqueue.c:1525:gst_queue_loop:<queue1> (queue1:src) wait for ADD: 0 of 0-200 buffers, 0 of 0-10485760 bytes, 0 of 0-1000000000 ns, 0 items
```

On the other hand, if I remove the encoder the pipeline plays fine but, of course, I would need to decode the video on the second and independent pipeline.

```
gst-launch-1.0 videotestsrc ! queue ! x264enc ! \
interpipesink name=vts \
interpipesrc listen-to=vts ! \
queue ! fakesink
```

Am I missing something or doing something wrong? Have you tried similar examples on your side or always with RAW data?

Thanks!

**Comment by TopperBG** [comment] 2020-06-05 13:33
gst-launch-1.0 videotestsrc is-live=true ! queue ! x264enc ! h264parse ! \
interpipesink name=vts ! \
interpipesrc listen-to=vts ! \
queue ! avdec_h264 ! autovideosink

**Comment by dagmcr** [comment] 2020-06-05 14:08
Thanks @TopperBG for the quick response. The tricks `is-live` + `h264parse` makes the pipeline play but still not able to see anything.

With the above pipeline it stops in second 2:

```
0:00:02.458764749 23822 0x55c18d897120 DEBUG                    bin gstbin.c:878:find_message:<pipeline0> we found a message 0x55c18d982b30 from vts matching types 00100000
0:00:02.458827463 23822 0x55c18d897120 DEBUG                    bin gstbin.c:919:bin_replace_message:<pipeline0> replace old message async-start from vts with async-done message
0:00:02.458841555 23822 0x55c18d897120 DEBUG                    bin gstbin.c:878:find_message:<pipeline0> we found a message 0x55c18d982ab0 from autovideosink0 matching types 00100000
0:00:02.458851187 23822 0x55c18d897120 DEBUG                    bin gstbin.c:3968:gst_bin_handle_message_func:<pipeline0> there are more async elements pending
0:00:02.458852447 23822 0x55c18d897360 DEBUG              GST_EVENT gstpad.c:5697:gst_pad_send_event_unchecked:<avdec_h264-0:sink> have event type segment event: 0x7f4808007200, time 0:00:00.000000000, seq-num 76, GstEventSegment, segment=(GstSegment)"GstSegment, flags=(GstSegmentFlags)GST_SEGMENT_FLAG_NONE, rate=(double)1, applied-rate=(double)1, format=(GstFormat)GST_FORMAT_TIME, base=(guint64)0, offset=(guint64)0, start=(guint64)3599999988463801, stop=(guint64)18446744073709551615, time=(guint64)0, position=(guint64)3599999988463801, duration=(guint64)18446744073709551615;";
0:00:02.458875671 23822 0x55c18d897360 DEBUG           videodecoder gstvideodecoder.c:1363:gst_video_decoder_sink_event:<avdec_h264-0> received event 17934, segment
0:00:02.458894488 23822 0x55c18d897360 DEBUG           videodecoder gstvideodecoder.c:1234:gst_video_decoder_sink_event_default:<avdec_h264-0> received TIME SEGMENT time segment start=999:59:59.988463801, offset=0:00:00.000000000, stop=99:99:99.999999999, rate=1.000000, applied_rate=1.000000, flags=0x00, time=0:00:00.000000000, base=0:00:00.000000000, position 999:59:59.988463801, duration 99:99:99.999999999
0:00:02.458906091 23822 0x55c18d897360 DEBUG               GST_PADS gstpad.c:5781:gst_pad_send_event_unchecked:<avdec_h264-0:sink> sent event, ret ok
0:00:02.458918710 23822 0x55c18d897360 DEBUG               GST_PADS gstpad.c:3936:push_sticky:<queue0:src> event segment marked received
0:00:02.458942853 23822 0x55c18d897360 TRACE             GST_TRACER :0:: queuelevel, queue=(string)queue0, size_bytes=(uint)0, max_size_bytes=(uint)10485760, size_buffers=(uint)0, max_size_buffers=(uint)200, size_time=(string)0:00:00.000000000, max_size_time=(string)0:00:01.000000000;
0:00:02.458961857 23822 0x55c18d897360 DEBUG         GST_SCHEDULING gstpad.c:4323:gst_pad_chain_data_unchecked:<avdec_h264-0:sink> calling chainfunction &gst_video_decoder_chain with buffer buffer: 0x7f4808230120, pts 1000:00:00.133333333, dts 999:59:59.966666667, dur 0:00:00.033333333, size 5348, offset 7144, offset_end none, flags 0x2000
0:00:02.458978067 23822 0x55c18d897360 DEBUG                  libav gstavviddec.c:1840:gst_ffmpegviddec_handle_frame:<avdec_h264-0> stored opaque values idx 1
0:00:02.459054881 23822 0x55c18d897120 DEBUG                GST_BUS gstbus.c:351:gst_bus_post:<bus1> [msg 0x7f4808132430] dropped
0:00:02.459066801 23822 0x55c18d897120 DEBUG               basesink gstbasesink.c:2368:gst_base_sink_wait_preroll:<vts> waiting in preroll for flush or PLAYING
0:00:02.459178099 23822 0x7f4808129900 DEBUG                  libav :0:: nal_unit_type: 9(AUD), nal_ref_idc: 0
0:00:02.459203435 23822 0x7f4808129900 DEBUG                  libav :0:: nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 2
0:00:02.459226455 23822 0x55c18d897360 DEBUG                  libav gstavviddec.c:748:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> getting buffer picture 0x7f480c01e140
0:00:02.459236768 23822 0x55c18d897360 DEBUG                  libav gstavviddec.c:753:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> opaque value SN 1
0:00:02.459245624 23822 0x55c18d897360 DEBUG           videodecoder gstvideodecoder.c:3559:gst_video_decoder_get_frame:<avdec_h264-0> frame_number : 1
0:00:02.459255111 23822 0x55c18d897360 DEBUG                  libav gstavviddec.c:573:gst_ffmpegviddec_video_frame_new:<avdec_h264-0> new video frame 0x7f480c07a440
0:00:02.459263413 23822 0x55c18d897360 DEBUG                  libav gstavviddec.c:779:gst_ffmpegviddec_get_buffer2:<avdec_h264-0> storing opaque 0x7f480c07a440
0:00:02.459319008 23822 0x7f4808129900 DEBUG                  libav :0:: no picture 
0:00:02.459344921 23822 0x55c18d897360 DEBUG                  libav gstavviddec.c:1687:gst_ffmpegviddec_video_frame:<avdec_h264-0> return flow ok, got frame: 0
0:00:02.459358278 23822 0x55c18d897360 DEBUG         GST_SCHEDULING gstpad.c:4329:gst_pad_chain_data_unchecked:<avdec_h264-0:sink> called chainfunction &gst_video_decoder_chain with buffer 0x7f4808230120, returned ok
0:00:02.459368892 23822 0x55c18d897360 DEBUG         queue_dataflow gstqueue.c:1516:gst_queue_loop:<queue0> queue is empty
```

While if I add queues around the encoder and the decoder, it goes a bit further:

```
GST_DEBUG="*:5,GST_TRACER:7" GST_TRACERS="queuelevel" \
gst-launch-1.0 videotestsrc is-live=true ! queue name=q1 ! x264enc ! queue name=q2 ! \
h264parse ! \
interpipesink name=vts \
interpipesrc listen-to=vts ! \
queue name=q3 ! \
avdec_h264 ! \
queue name=q4 ! \
autovideosink
```

logs:

```
0:00:04.531344645 24447 0x55bb20aef580 DEBUG           videotestsrc gstvideotestsrc.c:1165:gst_video_test_src_fill:<videotestsrc0> Timestamp: 0:00:03.733333333 = accumulated 0:00:00.000000000 + offset: 0:00:00.000000000 + running time: 0:00:03.733333333
0:00:04.531375283 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstclock.c:256:gst_clock_entry_new:<GstSystemClock> created entry 0x7f87b05ae530, time 3:52:11.074143527
0:00:04.531394172 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstclock.c:557:gst_clock_id_wait:<GstSystemClock> waiting on clock entry 0x7f87b05ae530
0:00:04.531415291 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstclock.c:1091:gst_clock_get_internal_time:<GstSystemClock> internal time 3:52:11.042002097
0:00:04.531433689 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstclock.c:1136:gst_clock_get_time:<GstSystemClock> adjusted time 3:52:11.042002097
0:00:04.531456697 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstsystemclock.c:710:gst_system_clock_id_wait_jitter_unlocked: entry 0x7f87b05ae530 time 3:52:11.074143527 now 3:52:11.042002097 diff (time-now) 32141430
0:00:04.531476561 24447 0x55bb20aef580 DEBUG               GST_POLL gstpoll.c:1414:gst_poll_wait: 0x55bb209c6990: timeout :0:00:00.032141430
0:00:04.563756694 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstsystemclock.c:741:gst_system_clock_id_wait_jitter_unlocked: entry 0x7f87b05ae530 unlocked, status 3, ret 0
0:00:04.563832548 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstsystemclock.c:765:gst_system_clock_id_wait_jitter_unlocked: entry 0x7f87b05ae530 unlocked after timeout
0:00:04.563904102 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstclock.c:1091:gst_clock_get_internal_time:<GstSystemClock> internal time 3:52:11.074486218
0:00:04.563938685 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstclock.c:1136:gst_clock_get_time:<GstSystemClock> adjusted time 3:52:11.074486218
0:00:04.563968760 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstsystemclock.c:787:gst_system_clock_id_wait_jitter_unlocked: entry 0x7f87b05ae530 finished, diff -342691
0:00:04.563992231 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstclock.c:565:gst_clock_id_wait:<GstSystemClock> done waiting entry 0x7f87b05ae530, res: 0 (ok)
0:00:04.564009800 24447 0x55bb20aef580 DEBUG              GST_CLOCK gstclock.c:368:_gst_clock_id_free: freed entry 0x7f87b05ae530
0:00:04.564029014 24447 0x55bb20aef580 DEBUG                basesrc gstbasesrc.c:2612:gst_base_src_get_range:<videotestsrc0> buffer ok
0:00:04.564107575 24447 0x55bb20aef580 DEBUG         GST_SCHEDULING gstpad.c:4323:gst_pad_chain_data_unchecked:<q1:sink> calling chainfunction &gst_queue_chain with buffer buffer: 0x7f87b05af480, pts 0:00:03.753538714, dts 99:99:99.999999999, dur 0:00:00.033333333, size 115200, offset 112, offset_end 113, flags 0x0
0:00:04.564134892 24447 0x55bb20aef580 DEBUG         queue_dataflow gstqueue.c:1241:gst_queue_chain_buffer_or_list:<q1> queue is full, waiting for free space
```

But it blocks because of `0:00:04.564134892 24447 0x55bb20aef580 DEBUG         queue_dataflow gstqueue.c:1241:gst_queue_chain_buffer_or_list:<q1> queue is full, waiting for free space`.

But looking into the queues with gst-shark, they all look empty except for q4 which I don't think data gets to there.

**Comment by tvlenin** [comment] 2020-06-05 14:46
Hi @dagmcr 

We are going to reproduce your issue and will come back to keep you updated.

Regards,
Lenin Torres

**Comment by dagmcr** [comment] 2020-06-05 15:15
Here a report of the 2 pipelines and one extra without a decoder:
```
gst-launch-1.0 videotestsrc is-live=true num-buffers=300 ! queue ! x264enc ! queue ! avdec_h264 ! autovideosink
```
![example1](https://user-images.githubusercontent.com/22496264/83892701-4def3a00-a74f-11ea-96d3-26d81a3ff07a.png)

```
gst-launch-1.0 videotestsrc is-live=true ! queue ! x264enc ! h264parse ! \
interpipesink name=vts \
interpipesrc listen-to=vts ! \
queue ! avdec_h264 ! autovideosink
```
> Note: this one plays but nothing is displayed.

![example2](https://user-images.githubusercontent.com/22496264/83892702-4e87d080-a74f-11ea-9430-d580fc6f502f.png)

```
gst-launch-1.0 videotestsrc is-live=true ! queue ! x264enc ! h264parse ! \
interpipesink name=vts \
interpipesrc listen-to=vts ! \
queue ! fakesink
```
![example3](https://user-images.githubusercontent.com/22496264/83892921-96a6f300-a74f-11ea-80a7-c4cd530ca24c.png)

Checking the numbers, looks like the interpipe components are blocking somehow the 'producer' pipeline if the decoder is present in the 'consumer' pipeline.

**Comment by tvlenin** [comment] 2020-06-05 15:30
@dagmcr 
Try with the following pipeline :

`gst-launch-1.0 videotestsrc ! queue  ! x264enc ! interpipesink name=vts interpipesrc listen-to=vts ! queue ! h264parse ! avdec_h264 ! autovideosink sync=false`

Please let me know if it works for you.

**Comment by dagmcr** [comment] 2020-06-05 16:28
Hi @tvlenin,

It didn't work. Here the log file with `GST_DEBUG=*:5`: 
[out.log](https://github.com/RidgeRun/gst-interpipe/files/4737360/out.log)

Please, notice the log "stopping pipeline manually" was added manually before pressing `ctrl-c`.

**Comment by tvlenin** [comment] 2020-06-05 21:21
Hi @dagmcr ,
The last pipeline don't show any video or the video is stopped?
Could you try same pipeline but removing the `sync=false` please.

**Comment by dagmcr** [comment] 2020-06-06 08:53
>The last pipeline don't show any video or the video is stopped?

In this case, the pipeline does not move to play. These are the logs:

```
Setting pipeline to PAUSED ...
0:00:00.081160732  6616 0x55f48cf294c0 FIXME                default gstutils.c:3980:gst_pad_create_stream_id_internal:<videotestsrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Pipeline is PREROLLING ...
0:00:00.081300500  6616 0x55f48cf29520 FIXME                default gstutils.c:3980:gst_pad_create_stream_id_internal:<interpipesrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Redistribute latency...
Redistribute latency...
^Chandling interrupt.
Interrupt: Stopping pipeline ...
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

With the next graph, I can clearly see the status of the elements are READY:
![test_ready_ready](https://user-images.githubusercontent.com/22496264/83939575-62c6de80-a7de-11ea-8700-709528d151a6.png)

These are the files generated:
*  `/tmp/0.00.00.079595937-gst-launch.NULL_READY.dot`
*  `/tmp/0.00.41.292125880-gst-launch.READY_READY.dot`

> Could you try same pipeline but removing the sync=false please.

Removing that parameter does not do anything. So, pipeline does not play and therefore, the video is not displayed.

However, adding `is-live=true` looks that it makes the pipeline play with or without `sync=false`. But it does not display any video:

```
Setting pipeline to PAUSED ...
0:00:00.081224210  7450 0x562eb54ec8c0 FIXME                default gstutils.c:3980:gst_pad_create_stream_id_internal:<videotestsrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:00.081327141  7450 0x562eb54ec920 FIXME                default gstutils.c:3980:gst_pad_create_stream_id_internal:<interpipesrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
Redistribute latency...
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:43.297467556
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
```

But it is not displaying anything because the pipeline is not in PLAYING state. Here the dot graph files generated:

*  `/tmp/0.00.43.450601199-gst-launch.PAUSED_READY.dot`
*  `/tmp/0.00.43.380399594-gst-launch.PAUSED_PAUSED.dot`
*  `/tmp/0.00.00.081275069-gst-launch.READY_PAUSED.dot`
*  `/tmp/0.00.00.079895380-gst-launch.NULL_READY.dot`

The status for the `/tmp/0.00.43.380399594-gst-launch.PAUSED_PAUSED.dot` is actuallly PAUSED:
![test_paused_paused](https://user-images.githubusercontent.com/22496264/83940316-e636fe80-a7e3-11ea-9613-370daee41f91.png)

**Comment by jcaballeros** [comment] 2020-08-03 21:55
Hi @dagmcr,

Are you still seeing this issue? If so, could you please share your GStreamer and gst-interpipe versions?

Regards,
Jennifer

**Comment by jcaballeros** [comment] 2020-08-24 21:02
Closing issue. Feel free to reopen if necessary.

**Closed by jcaballeros** 2020-08-24 21:02 UTC

**Comment by yuyou** [comment] 2021-03-15 12:46
@dagmcr Just curious, which tool you used to generate the dot graph with the data transferred? It looks so useful to debug the pipeline.

I feel this issue was closed without a working solution. I managed to make it work with following 3 key points:

1.  "is-live=true" to interpipesrc;
2.  use "videoconvert" before "autovideosink" or any other video sinks;
3. use "sync=false" to the video sink;

See my working test script:
```
gst-launch-1.0 videotestsrc pattern=ball is-live=true ! queue ! x264enc tune=zerolatency byte-stream=true key-int-max=15 ! h264parse config-interval=-1 ! interpipesink name=vts interpipesrc listen-to=vts is-live=true format=time allow-renegotiation=false ! queue ! h264parse ! avdec_h264 ! videoconvert ! fpsdisplaysink sync=false
```

OS: Ubuntu 18.04
Gstreamer: 1.18.2 (built from source with all plugins and gst-libav)
Interpipe: 1.1.3 (the latest from the master branch)

**Comment by TopperBG** [comment] 2021-03-15 12:56
> @dagmcr Just curious, which tool you used to generate the dot graph with the data transferred? It looks so useful to debug the pipeline.
> 

https://developer.ridgerun.com/wiki/index.php/GStreamer_Debugging#Create_DOT_file_to_see_exact_pipeline_and_capabilities_used

**Comment by dagmcr** [comment] 2021-03-15 13:05
Hi @yuyou,

> @dagmcr Just curious, which tool you used to generate the dot graph with the data transferred? It looks so useful to debug the pipeline.

I used `gst-instruments`: https://github.com/kirushyk/gst-instruments.

> See my working test script:

Your script uses `x264` which is a software encoder. If you try to decouple by using a software encoder/decoder it won't fail.

The problem is when using `vaapih264enc`. Actually, I haven't tried yet but the problem should be solved by following this approach: https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/273#note_598059

**Comment by mariannasb** [comment] 2021-05-28 12:14
I'm also having the same issue

This pipeline shows no data in the `fakesink`:
```
gst-launch-1.0 videotestsrc is-live=true pattern=ball ! video/x-raw,framerate=30/1,format=NV12 ! timeoverlay ! tee name=t ! queue ! videoconvert ! ximagesink sync=0 t. ! queue ! x264enc key-int-max=30 speed-preset=1 tune=zerolatency ! video/x-h264,profile=high ! h264parse ! queue ! interpipesink name=vtest1 sync=true async=false interpipesrc listen-to=vtest1 name=vselect is-live=true stream-sync=passthrough-ts ! queue ! fakesink dump=1 sync=1
```
If I change to `sync=0` in the `fakesink` it will dump data.

But doesn't this points to problems in the timings/clock/synchronization?

Because I seem to have problems with  timings/clock/synchronization when I'm trying to change between live sources and file sources: https://github.com/RidgeRun/gst-interpipe/issues/88
