### ISSUE TITLE
imxv4l2src related

### ISSUE THREAD

**Issue by erprakash2006** [RidgeRun/gst-interpipe#32] opened 2019-06-05 06:54 UTC
Hi,

I would like to use interpipe src and sink for my application in imx platform.

I used like below pipeline:

  sink = GST_ELEMENT (gst_parse_launch ("imxv4l2src device=/dev/v4l/by-path/platform-1ffc000.pcie-pci-0000:01:00.0-video-index0 ! video/x-raw,format=(string)UYVY,width=720,height=576,framerate=(fraction)25/1,interlace-mode=(string)interleaved ! queue ! interpipesink name=sink async=true", &error));
  src1 = GST_ELEMENT (gst_parse_launch ("interpipesrc listen-to=sink is-live=true ! queue ! video/x-raw,format=(string)UYVY,width=720,height=576,framerate=(fraction)25/1,interlace-mode=(string)interleaved ! imxvideoconvert_ipu ! overlaysink sync=false", &error));

	Unfortunately, I see the below error:
	
0:00:06.782479250 10006    0xba260 WARN                 imxv4l2 gstimxv4l2.c:1885:gst_imx_v4l2_queue_gstbuffer: new buffer (0x73807bf0) use the same memblk(0x738016bc) with queued buffer(0x73807b50)
0:00:06.782605593 10006    0xba260 WARN                 imxv4l2 gstimxv4l2.c:1888:gst_imx_v4l2_queue_gstbuffer: gstbuffer(0x73807b50) for (0x76c79a50) not dequeued yet but queued again, index(1937800016).
0:00:06.782670265 10006    0xba260 ERROR                imxv4l2 gstimxv4l2.c:1770:imx_v4l2_do_queue_buffer: queue v4l2 buffer failed.
0:00:06.782713602 10006    0xba260 ERROR                imxv4l2 gstimxv4l2.c:1892:gst_imx_v4l2_queue_gstbuffer: queue gstbuffer (0x73807bf0) failed.

(gstr:10006): GStreamer-CRITICAL **: gst_buffer_iterate_meta: assertion 'buffer != NULL' failed

(gstr:10006): GStreamer-CRITICAL **: gst_buffer_add_meta: assertion 'buffer != NULL' failed
Killing all inferiors
logout

	I guess, it is because of imx v4l2 source expects its hardware buffer to be released. 
	Because it has limited buffers. 
	
	Could you please update me with any possible solutions for my issue ?
	Also please suggest how to use interpipe src/sink with imxv4l2src

Also below pipeline works like champ: 
  //sink = GST_ELEMENT (gst_parse_launch ("videotestsrc pattern=1 is-live=true ! video/x-raw,format=(string)I420,width=(int)320,height=(int)240,framerate=(fraction)15/1 ! queue ! interpipesink name=sink forward-events=true", &error));
  //src1 = GST_ELEMENT (gst_parse_launch ("interpipesrc listen-to=sink is-live=true ! queue ! video/x-raw,format=(string)I420,width=(int)320,height=(int)240,framerate=(fraction)15/1 ! imxvideoconvert_ipu ! overlaysink sync=false", &error));
  
  Thanks in advance.
  Prakash

**Comment by lleoncr** [comment] 2019-06-06 15:59
Hi Prakash

We are going to reproduce your error and will come back to keep you updated.

Regards,
Leon

**Comment by erprakash2006** [comment] 2019-06-07 05:46
Dear Leon, Thanks for your update. Kindly let me know if you need any details.

Regards,
Prakash B

**Comment by lleoncr** [comment] 2019-06-17 13:36
Hi @erprakash2006 

Could you give us your GStreamer and Linux Kernel versions? You can run the following commands:

```
gst-launch-1.0 --version
uname -a
```

Thank you in advance.

Leon.

**Comment by erprakash2006** [comment] 2019-06-17 15:06
Hi Leon,

Please find the required info below:

Product Info: i.MX6Q/D/S
gst-launch-1.0 version 1.10.4
GStreamer 1.10.4

uname -a:
Linux 4.1.15-rt18-2.0.3-1_2_1+gb63f3f5 #2 SMP PREEMPT RT Tue May 14 15:35:05 CEST 2019 armv7l GNU/Linux

Kindly let me know if you need any more details.

Thanks and Regards,
Prakash B

**Comment by lleoncr** [comment] 2019-06-26 21:23
Hi @erprakash2006 

Sorry for the late reply. We have been working on solving the issue, but it has taken time to find the origin, due to `imxv4l2src` belongs to a series of plugins of the recipe `imx-fsl-plugins`. Most of the plugins which belongs to that recipe are discontinued. Instead of that, I suggest you use the `imxv4l2videosrc`, which can be found in [Freescale/gstreamer-imx](https://github.com/Freescale/gstreamer-imx).

Let me show you an example:

`gst-launch-1.0  imxv4l2videosrc device=/dev/video0 ! video/x-raw,format=I420,width=320,height=240,framerate=15/1 ! queue ! interpipesink name=sink forward-events=true interpipesrc listen-to=sink is-live=true ! queue ! video/x-raw,format=I420,width=320,height=240,framerate=15/1 ! imxpxpvideosink`

Also, you can use our **gstreamer daemon** for prototyping an application with multiple sources and a single sink. For examples and more info, you can take a look at: [https://developer.ridgerun.com/wiki/index.php?title=GstInterpipe_-_Example_1:_CCTV](https://developer.ridgerun.com/wiki/index.php?title=GstInterpipe_-_Example_1:_CCTV).

Hope this can help you in your application. Let me know if you need more help.

Have a wonderful day,
Leon.

**Comment by erprakash2006** [comment] 2019-07-04 11:56
Hi Leon,

Currently in our platform, we do not have imxv4l2videosrc and imxpxpvideosink. So i would not be able to use it. 
And as you mentioned that "it has taken time to find the origin", I assume you found the origin of the problem. Could you please share the root cause of the problem. And probable solutions to the problem if possible.

Thanks in advance.
Have a nice day.
With Regards,
Prakash B

**Comment by lleoncr** [comment] 2019-07-04 18:04
Hi @erprakash2006,

It is basically about how imxv4l2src is negotiating the buffers. There are reports of issues related to it in the NXP forums. Also, this element belongs to a group of plugins which is currently deprecated: there is no any updates since Yocto Daisy. 

Our suggestion in this case is to use the updated version of the plugins for IMX. You can find them at: Freescale/gstreamer-imx

My test environment was:

Yocto Version: Rocko
GStreamer: 1.10.4
Kernel: Linux 4.1.15

Regards,
Leon.

**Comment by jcaballeros** [comment] 2020-08-25 18:05
Closing, feel free to reopen if necessary.

**Closed by jcaballeros** 2020-08-25 18:05 UTC
